// Mocks generated by Mockito 5.4.6 from annotations
// in encrypted_notebook/test/integration/sync_flow_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:encrypted_notebook/data/remote/firebase_client.dart' as _i4;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_2<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReference_3 extends _i1.SmartFake implements _i3.Reference {
  _FakeReference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseClient extends _i1.Mock implements _i4.FirebaseClient {
  MockFirebaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  _i2.CollectionReference<Map<String, dynamic>> notesCollection(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #notesCollection,
          [uid],
        ),
        returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #notesCollection,
            [uid],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> vaultCollection(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #vaultCollection,
          [uid],
        ),
        returnValue: _FakeCollectionReference_0<Map<String, dynamic>>(
          this,
          Invocation.method(
            #vaultCollection,
            [uid],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> keysDocument(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #keysDocument,
          [uid],
        ),
        returnValue: _FakeDocumentReference_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #keysDocument,
            [uid],
          ),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> pushNote(
    String? uid,
    Map<String, dynamic>? noteData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNote,
          [
            uid,
            noteData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>> watchNotes(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchNotes,
          [uid],
        ),
        returnValue:
            _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>> getNote(
    String? uid,
    String? noteId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNote,
          [
            uid,
            noteId,
          ],
        ),
        returnValue:
            _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_2<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getNote,
            [
              uid,
              noteId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<void> deleteNote(
    String? uid,
    String? noteId,
    DateTime? deletedAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [
            uid,
            noteId,
            deletedAt,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pushVaultItem(
    String? uid,
    Map<String, dynamic>? vaultData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushVaultItem,
          [
            uid,
            vaultData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>> watchVault(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchVault,
          [uid],
        ),
        returnValue:
            _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>.empty(),
      ) as _i5.Stream<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>> getVaultItem(
    String? uid,
    String? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVaultItem,
          [
            uid,
            itemId,
          ],
        ),
        returnValue:
            _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_2<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getVaultItem,
            [
              uid,
              itemId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<void> deleteVaultItem(
    String? uid,
    String? itemId,
    DateTime? deletedAt,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteVaultItem,
          [
            uid,
            itemId,
            deletedAt,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> uploadKeyParams(
    String? uid,
    Map<String, dynamic>? keyParams,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadKeyParams,
          [
            uid,
            keyParams,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> downloadKeyParams(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadKeyParams,
          [uid],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>> watchKeyParams(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchKeyParams,
          [uid],
        ),
        returnValue:
            _i5.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>>.empty(),
      ) as _i5.Stream<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i3.Reference userFilesRef(
    String? uid,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #userFilesRef,
          [
            uid,
            filename,
          ],
        ),
        returnValue: _FakeReference_3(
          this,
          Invocation.method(
            #userFilesRef,
            [
              uid,
              filename,
            ],
          ),
        ),
      ) as _i3.Reference);

  @override
  _i5.Future<String> uploadFile(
    String? uid,
    String? filename,
    List<int>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            uid,
            filename,
            data,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadFile,
            [
              uid,
              filename,
              data,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i7.Uint8List?> downloadFile(
    String? uid,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [
            uid,
            filename,
          ],
        ),
        returnValue: _i5.Future<_i7.Uint8List?>.value(),
      ) as _i5.Future<_i7.Uint8List?>);

  @override
  _i5.Future<void> deleteFile(
    String? uid,
    String? filename,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [
            uid,
            filename,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
